# Generated by Django 5.2.6 on 2026-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='faculty_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
