# Generated by Django 5.2.5 on 2025-09-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Lab'), ('seminar hall', 'Seminar Hall'), ('reading room', 'Reading Room'), ('auditorium', 'Auditorium')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.block')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('room_number', 'block')},
            },
        ),
    ]
