# Generated by Django 5.2.6 on 2026-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Lab', 'Lab'), ('Seminar Hall', 'Seminar Hall'), ('Reading Room', 'Reading Room'), ('Auditorium', 'Auditorium'), ('Staff Room', 'Staff Room'), ('Office', 'Office'), ('Laboratory', 'Laboratory'), ('Computer Lab', 'Computer Lab'), ('Exam Cell', 'Exam Cell'), ('Mobile Lab', 'Mobile Lab'), ('Placement Cell', 'Placement Cell'), ('IQAC', 'IQAC')], max_length=50),
        ),
    ]
